### ISSUE TITLE
Resque Monitoring Intermittent "Plugin Failed To Run"

### ISSUE THREAD

**Issue by dobrite** [scoutapp/scout-client#31]
I'm getting intermittent failures "Plugin Failed To Run" when using the Resque Monitoring Plugin. The stack-trace is at the end of this issue.

I filed an issue with [multi json](https://github.com/intridea/multi_json/issues/170), but I'm not sure where the issue lies. One install of the plugin fails all the time, but all the rest (~5) only fail intermittently.

It looks like the scout client is using Ruby 1.9.1 and Multi Json 1.12.1. My general question is where do these gems get installed from? Is it something that `scout-client` handles or does `scout-client` assume they are already installed?

I'm looking to debug the issue, but outside of manually editing the gem file on the server(s), I'm at a loss. Any input would be appreciated!

Thanks,
Dave

```
NameError: uninitialized constant Class::OptionsCache 
/var/lib/gems/1.9.1/gems/multi_json-1.12.1/lib/multi_json/adapter.rb:43:in `cached_load_options' 
/var/lib/gems/1.9.1/gems/multi_json-1.12.1/lib/multi_json/adapter.rb:21:in `load' 
/usr/lib/ruby/vendor_ruby/multi_json.rb:120:in `load' 
/var/lib/gems/1.9.1/gems/resque-1.26.0/lib/resque.rb:44:in `decode' 
/var/lib/gems/1.9.1/gems/resque-1.26.0/lib/resque/worker.rb:35:in `decode' 
/var/lib/gems/1.9.1/gems/resque-1.26.0/lib/resque/worker.rb:82:in `block in working' 
/var/lib/gems/1.9.1/gems/resque-1.26.0/lib/resque/worker.rb:80:in `map' 
/var/lib/gems/1.9.1/gems/resque-1.26.0/lib/resque/worker.rb:80:in `working' 
/var/lib/gems/1.9.1/gems/resque-1.26.0/lib/resque.rb:468:in `working' 
/var/lib/gems/1.9.1/gems/resque-1.26.0/lib/resque.rb:489:in `info' 
Resque Monitoring:21:in `build_report' 
/usr/share/scout/ruby/scout-client/lib/scout/plugin.rb:222:in `run' 
/usr/share/scout/ruby/scout-client/lib/scout/server.rb:461:in `block in process_plugin' 
/usr/lib/ruby/1.9.1/timeout.rb:69:in `timeout' 
/usr/share/scout/ruby/scout-client/lib/scout/server.rb:460:in `process_plugin' 
/usr/share/scout/ruby/scout-client/lib/scout/server.rb:303:in `block in run_plugins_by_plan' 
/usr/share/scout/ruby/scout-client/lib/scout/server.rb:301:in `each' 
/usr/share/scout/ruby/scout-client/lib/scout/server.rb:301:in `run_plugins_by_plan' 
/usr/share/scout/ruby/scout-client/lib/scout/command/run.rb:51:in `run' 
/usr/share/scout/ruby/scout-client/lib/scout/command.rb:169:in `dispatch' 
/usr/share/scout/ruby/scout-client/bin/scout:17:in `
```

**Comment by ErebusBat** [comment]
I am also running into this issue, was there any progress on this?

**Comment by andre** [comment]
@ErebusBat thanks for the report and the discussion over on the Resque thread.

To anyone else experiencing this issue, please upgrade your `multi_json` to `1.11.2`. And of course, ping us if you still have issues.
